augments:
  inters:
  - 0
  - 1
  - 2
  - 4
  - 3
  max_face: 256
  min_face: 6
  rotation: 5
  symmetry:
  - 1
  - 0
  - 2
  - 4
  - 3
batch_size: 256
device: null
dsize:
- 320
- 320
encode_mean: null
encode_std:
- 0.1
- 0.1
- 0.2
- 0.2
eval_interval: 100
fsizes:
- - 40
  - 40
- - 20
  - 20
- - 10
  - 10
- - 5
  - 5
gamma: 0.1
iou_threshold: 0.35
layouts:
- - 10
  - 16
  - 24
- - 32
  - 48
- - 64
  - 96
- - 128
  - 192
  - 256
lr: 0.2
model:
  args: []
  kwargs: {}
  name: Slim
momentum: 0.9
num_workers: 8
start_step: 0
strides:
- 8
- 16
- 32
- 64
test:
  image_dir: path/to/image/
  iou_threshold: 0.5
  result_dir: result
  score_threshold: 0.1
  short_size: 320
total_steps: 10000
train_image: /dockerdata/WIDER_train/images
train_label: /dockerdata/train/label.txt
val_image: /dockerdata/WIDER_val/images
val_label: /dockerdata/val/label.txt
weight_decay: 0.0005
workdir: /cfs/cfs-30592a081/venus/xvision/fd
